[[redirects]]
from = "/*"
to = "/index.html"
status = 200 



[[headers]]
  for = "https://authenticationtestassignment.netlify.app"
  [headers.values]
    Access-Control-Allow-Origin= "https://authenticationtestassignment.netlify.app"
    Access-Control-Allow-Credentials="true"

    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS,PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"